### ISSUE TITLE
Unlabeled Data Download Issue

### ISSUE THREAD

**Issue by typ1012** [LoTE-Animal/LoTE-Animal.github.io#3]
Thanks for your good work!
The download link for the unlabeled dataset is not working.

**Comment by LoTE-Animal** [comment]
已解决，请刷新页面查看。











刘丹
***@***.***

签名由 网易灵犀办公 定制









Original:
From：yptang ***@***.***>Date：2023-12-20 22:06:49(中国 ***@***.***>Cc：Subscribed ***@***.***>Subject：[LoTE-Animal/LoTE-Animal.github.io] Unlabeled Data Download Issue (Issue #3)
Thanks for your good work!
 The download link for the unlabeled dataset is not working.
